### ISSUE TITLE
kapt issue

### ISSUE THREAD

**Issue by guggi27** [ibrajix/DirectCurrencyConverter#1]
![image](https://user-images.githubusercontent.com/42814870/135161573-97890673-ede8-4004-b2fa-39a881298eea.png)

This issue is keeping the app not run able from android studio

**Comment by ibrajix** [comment]
> ![image](https://user-images.githubusercontent.com/42814870/135161573-97890673-ede8-4004-b2fa-39a881298eea.png)
> 
> This issue is keeping the app not run able from android studio

Hello.

The error isn't descriptive enough but I think I have faced similar issue in the past.

Please see these:

1. https://stackoverflow.com/questions/62995176/kotlin-execution-failed-for-task-appkaptdebugkotlin?rq=1

2.  https://stackoverflow.com/questions/46850060/errorexecution-failed-for-task-appkaptdebugkotlin

If the above didnt work, I'll suggest you target API level 30 instead of 31 (as a last resort).
